### ISSUE TITLE
Facebook mentions

### ISSUE THREAD

**Issue by Bjornskjald** [miscord/miscord#265]
mention people on Messenger from Discord

**Comment by jtylr** [comment]
@Bjornskjald - Any progress on this one? Was about to crack open the code to see if I could make `@everyone` work from discord -> Messenger but wasn't sure what the messenger library supported.

**Comment by jtylr** [comment]
Yep, totally agree - If I have a chance to look at this, I'll open a PR with a config option for you.

**Comment by tatumalenko** [comment]
Does the Messenger side API or library currently have that functionality possible (to tag a user on Messenger) yet? I browsed the API briefly but didn't see it. I'd be willing to take a crack at this.

**Comment by Bjornskjald** [comment]
I was trying to implement it in ChatPlug/libfb, but wasn't able to, we apparently use a wrong endpoint for sending messages

**Comment by jtylr** [comment]
I had a beta one-way version of tagging working [here](https://github.com/jtylr/miscord/commit/474b151042c715cc145a1c69754c5fba9b973a21) - It's in the wrong file and has only been hacked together as a test. Facebook has since blocked the facebook account I was using though so I've not worked on it since.

By no means is that code clean, it doesn't contain a config option (it should) but it may show how to do this.

I do wonder if mass-tagging users is what caused Facebook to flag the account as a bot though. Mass-tagging could potentially look like a spam-bot action. YMMV.

**Comment by Bjornskjald** [comment]
We're using a different library now, based on mobile Messenger instead of the web version, so there's a different API than before

**Comment by jtylr** [comment]
Ah, my bad - I guess that happened in the last week or two. I'll have to update and see if that can do anything new!

**Comment by Bjornskjald** [comment]
Fixed in https://github.com/miscord/miscord/commit/ede8d6358fc680806032fc9433b26e1dc46f5d30.
