### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by Astrareach** [miscord/miscord#459]
**Hi, we are getting**
`AssertionError [ERR_ASSERTION]: Method 'GET' already declared for route '/connections/'`
**error** on the console. Launch on npm. The connexion is OK to Discord and Messenger**

**Here is the full log :** https://pastebin.com/ipafhGvy

**To Reproduce**
1. Configure the file
2. Launch

**Expected behavior**
It should work

**Screenshots**

**Specifications:**
 - OS:
Debian 9

 - Version:
Miscord 5.0.4

 - Node.js version:
v12.15.0

**Comment by jeansordes** [comment]
+1, same error here :/

**Comment by jeansordes** [comment]
~~I think you installed it with `npm i -g miscord`, and if you pay attention you will find that there is an error when you install it~~ (edit : nope, the problem is not because of it, my mistake)

As an alternative solution you can clone this repository to your machine, and then run this local version :
```
git clone https://github.com/miscord/miscord
cd miscord
npm install
npm start
```
And for the subsequent runs you can use `npm start` (before placing yourself in this folder before running it)

But it is still an issue that needs to be fixed

**Comment by CartoonChess** [comment]
I was encountering the same error and found it happens when the "api" object is included in config.json. This seems to happen regardless of port and whether there's any other web services running or not. Removing the api object from the config file solves the error, but leaves the web interface inaccessible.
